In [16]:
import pandas as pd

# 指定したexcelを読み込んで表示する
df = pd.read_excel("/content/matsuda.xlsx")
print(df)

          日にち  労働時間
0  2023-01-01     0
1  2023-01-02     7
2  2023-01-03    10
3  2023-01-04     8
4  2023-01-05     5
5  2023-01-06     4
6  2023-01-07     3
7  2023-01-08     6
8  2023-01-09     1
9  2023-01-10     4
10 2023-01-11     1
11 2023-01-12     1
12 2023-01-13     9
13 2023-01-14     0
14 2023-01-15     9
15 2023-01-16     8
16 2023-01-17    10
17 2023-01-18     9
18 2023-01-19     2
19 2023-01-20     3
20 2023-01-21     4
21 2023-01-22     2
22 2023-01-23     3
23 2023-01-24     5
24 2023-01-25     5
25 2023-01-26     6
26 2023-01-27     9
27 2023-01-28     4
28 2023-01-29     6
29 2023-01-30     5
30 2023-01-31     4

In [17]:
# excelの中から、指定したsheetを読み込む
df = pd.read_excel("/content/matsuda.xlsx", sheet_name = "202302")
print(df)

          日にち  労働時間
0  2023-02-01     2
1  2023-02-02     4
2  2023-02-03     9
3  2023-02-04     3
4  2023-02-05     5
5  2023-02-06     5
6  2023-02-07     5
7  2023-02-08     1
8  2023-02-09     4
9  2023-02-10     8
10 2023-02-11     5
11 2023-02-12     4
12 2023-02-13     9
13 2023-02-14     8
14 2023-02-15     7
15 2023-02-16     3
16 2023-02-17     2
17 2023-02-18     3
18 2023-02-19     1
19 2023-02-20     9
20 2023-02-21     4
21 2023-02-22     8
22 2023-02-23     8
23 2023-02-24     4
24 2023-02-25     9
25 2023-02-26     3
26 2023-02-27     7
27 2023-02-28     2

In [19]:
# すべてのシートを読み込みたい場合
all_df = pd.read_excel("/content/masuda.xlsx", sheet_name =None)
print(all_df)

{'202301':           日にち  労働時間
0  2023-01-01     5
1  2023-01-02     9
2  2023-01-03     3
3  2023-01-04     4
4  2023-01-05     7
5  2023-01-06     3
6  2023-01-07     3
7  2023-01-08     1
8  2023-01-09     9
9  2023-01-10     9
10 2023-01-11     7
11 2023-01-12     6
12 2023-01-13     8
13 2023-01-14     3
14 2023-01-15     9
15 2023-01-16    10
16 2023-01-17     8
17 2023-01-18     5
18 2023-01-19    10
19 2023-01-20     0
20 2023-01-21     6
21 2023-01-22     4
22 2023-01-23     2
23 2023-01-24     0
24 2023-01-25     2
25 2023-01-26     9
26 2023-01-27     9
27 2023-01-28     4
28 2023-01-29     6
29 2023-01-30     6
30 2023-01-31     8, '202302':           日にち  労働時間
0  2023-02-01     3
1  2023-02-02     5
2  2023-02-03     0
3  2023-02-04     3
4  2023-02-05     4
5  2023-02-06     3
6  2023-02-07     9
7  2023-02-08     7
8  2023-02-09     2
9  2023-02-10     6
10 2023-02-11     3
11 2023-02-12     2
12 2023-02-13    10
13 2023-02-14     6
14 2023-02-15     6
15 2023-02-16     7
16 2023-02-17     0
17 2023-02-18     7
18 2023-02-19     8
19 2023-02-20     8
20 2023-02-21    10
21 2023-02-22     7
22 2023-02-23     2
23 2023-02-24     4
24 2023-02-25     0
25 2023-02-26     2
26 2023-02-27     4
27 2023-02-28     1, '202303':           日にち  労働時間
0  2023-03-01     7
1  2023-03-02     8
2  2023-03-03     3
3  2023-03-04     3
4  2023-03-05     3
5  2023-03-06     7
6  2023-03-07     1
7  2023-03-08     1
8  2023-03-09     1
9  2023-03-10     7
10 2023-03-11     1
11 2023-03-12     6
12 2023-03-13     8
13 2023-03-14     4
14 2023-03-15     3
15 2023-03-16     3
16 2023-03-17     5
17 2023-03-18     4
18 2023-03-19     9
19 2023-03-20     2
20 2023-03-21     1
21 2023-03-22    10
22 2023-03-23     7
23 2023-03-24     7
24 2023-03-25     1
25 2023-03-26     8
26 2023-03-27     8
27 2023-03-28     9
28 2023-03-29     1
29 2023-03-30    10
30 2023-03-31     1, '202304':           日にち  労働時間
0  2023-04-01     7
1  2023-04-02     9
2  2023-04-03     2
3  2023-04-04     6
4  2023-04-05     8
5  2023-04-06     7
6  2023-04-07     4
7  2023-04-08     8
8  2023-04-09     4
9  2023-04-10     8
10 2023-04-11     8
11 2023-04-12     4
12 2023-04-13     9
13 2023-04-14     6
14 2023-04-15     8
15 2023-04-16     4
16 2023-04-17     4
17 2023-04-18     2
18 2023-04-19     1
19 2023-04-20     2
20 2023-04-21     9
21 2023-04-22     2
22 2023-04-23     1
23 2023-04-24     9
24 2023-04-25     9
25 2023-04-26     4
26 2023-04-27     4
27 2023-04-28     4
28 2023-04-29    10
29 2023-04-30     8}